services:
  # Frontend React application
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - server
    networks:
      - coderunner-network

  # Backend API server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
    networks:
      - coderunner-network

networks:
  coderunner-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 